### ISSUE TITLE
Dragging from upper right panel into main canvas leads to strange behavior

### ISSUE THREAD

**Issue by irisiflimsi** [RPTools/tokentool#10]
What happens looks consistent to a developer but a layman would consider this sureal.
1) Drag from "preview" into main canvas and drop
2) Modify sizes

I propose to make the preview non-draggable. I don't think this is intentional. In fact, when a token is copied from the main canvas, this preview is actually what is dropped. This drop on the main canvas may be intentional with copy and paste, but the drop from the preview is mostly accidental.

At least a one-step undo would be great here too.

**Comment by JamzTheMan** [comment]
Make preview non-draggable? Absolutely not! :)

This is the #1 way to get the token easily into MapTool.  It's meant to drag the finished token either to MapTool or a file location (or into e-mail or other application).

I suppose we could prevent dragfrom preview into main canvas but othewise all DnD events are purposely coded. (Also, this is how TokenTool 1.x worked as well)

**Comment by irisiflimsi** [comment]
Ctrl-C and Ctrl-V doesn't work? I understand the ease of DnD, but it shouldn't be dragged onto the main canvas, I think.

But I am not really using token tool, to be honest, so listen to your main users instead, whether this is a problem or an artifact found by an inexperienced tester.

**Comment by Azhrei** [comment]
Using keystrokes requires the ability to "select" something, or just assume that the Preview window is always selected...

I think disallowing the drag into the main window from the preview window makes the most sense.  And it should be pretty easy to detect the source of the drop as 'self'.

**Comment by JamzTheMan** [comment]
Granted, dragging the preview to the main canvas just replaces the existing portrait to be used.

This *could* be used for some sort of "effect".  I have users who already used TokenTool to create new "overlays" to use within TT so there may be use cases for this.

Remember, just because one person doesn't use a tool a certain way doesn't mean it should be limited for others. #optionsForAll! :)

**Comment by irisiflimsi** [comment]
By all means, do as you please here. I just fumbled around to see how you use JFX. And then I found the combo 1. drop preview on main. 2. resize token. That leads to reverse zooming into and out-of by the preview and main canvas. This is an "effect" of sorts and looks like a caleidoscope. Surely not intentional though. But that's what "playing around with it" leads to. At least when I'm in control :-)

**Comment by Azhrei** [comment]
As long as the app doesn't crash, I suppose we can leave it.  It might react strangely but, as Jamz says, I can see people quirks like these and taking advantage of them; as long as nothing breaks, it's probably fine. :)

**Comment by JamzTheMan** [comment]
FYI: I'm 99% sure this was the behavior in TokenTool 1.x and it didn't cause anyone any issues. :)

**Comment by Phergus** [comment]
That's true.  You could drag from the preview down into the composition area and add ring after ring after ring until the little portrait was too small to see anymore.
