### ISSUE TITLE
TokenTool cannot handle UTF8 strings in file names

### ISSUE THREAD

**Issue by wdmartin** [RPTools/TokenTool#122]
**Describe the bug**
When dragging a token from a file whose original name contains accented characters, the accented characters are stripped and replaced with underscores.

**To Reproduce**
1. Name an image file something with special characters.  For example: "Nénuphar di Hevonen.jpg".
2. Drag it into TokenTool.  Size and position it to taste.
3. Drag the token from the preview area to a folder.
4. Observe that the resulting file name is "N_nuphar di Hevonen.png", as the é has been converted to a _.

**Expected behavior**
It retains the original characters.

**TokenTool Info**
- Version: 2.1 - not sure if there's a newer one out

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by JamzTheMan** [comment]
Fixed for next release, relaxed the file name filter.

**Comment by Phergus** [comment]
Tested under 2.2 develop with this PNG image named: `hyena-headÀÇËÐÖæñ.png`

![hyena-headÀÇËÐÖæñ](https://user-images.githubusercontent.com/34379254/125330982-a571b900-e304-11eb-8bd6-fd931ac048c1.png)

Name is correct in TT as well as in MT when dragged into it from TT.
