### ISSUE TITLE
Change Portrait button stopped working

### ISSUE THREAD

**Issue by Snuzzgrot** [RPTools/TokenTool#136]
The change portrait button has stopped working

I have a portrait in place. i click on change portrait. nothing happens. 

i expect the window to select a file to open up. it doesnt.

Token tool version 2.1
Install NEW removed previous version to ry and fix problem,

Windows 10

**Comment by Snuzzgrot** [comment]
the new feature selecting a picture from a pdf, within the app, works, but the change portrait button still doesn't work even after changing the image this way ( i thought it may be a problem with the current image, but no.)

**Comment by Phergus** [comment]
From the Help menu, select Reset Settings and see if that fixes it.  It sounds like the last location a portrait was loaded from isn't there any more, a thumb drive, external drive or network share perhaps.   TokenTool does create a log file and that may have information.

**Comment by Snuzzgrot** [comment]
Thankyou, that seems to have worked. Full fix involved uninstalling 2.1, installed, 2.0, installed 2.1, Tried reset settings no joy. Uninstalled 2.1, uninstalled 2.0. Reinstalled 2.1 ...no joy,,, reset settings ...JOY...seems fixed!
