### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by ericw83** [RPTools/tokentool#14]
I am running Token tool v2.0 and up until this morning. It will not open, I see the loading screen, but then it minimizes and I see it on the windows bar on task bar but I can't ever get a window to open so that I can create tokens.

**Comment by Phergus** [comment]
I think you are saying that it was working but isn't now.  Were you using a different display or perhaps two displays the last time you used it?

With it showing on the task bar, right-click on an empty area of the task bar and select "Show windows side-by-side".  Does that make it appear?

**Comment by Phergus** [comment]
Your log tells you exactly what the problem is:
`2018-11-17 14:01:13.788 [JavaFX Application Thread] INFO  net.rptools.tokentool.AppPreferences - Restoring window position x, y: -32000.0, -32000.0`

I doubt you have a display that goes to -32000, -32000.  :)   So it's displayed way, way off screen.

Did you try my suggestion above?

**Comment by Shotty4Life** [comment]
You mean "Show windows side-by-side" ? Yeah I did, but that didn't make it appear.
Is there somewhere I can try and manually change those settings?

**Comment by Phergus** [comment]
Check the registry here:
`Computer\HKEY_CURRENT_USER\Software\JavaSoft\Prefs\token/Tool\control\main/Frame`

**Comment by Shotty4Life** [comment]
Ok, I found that. 
The keys were REG_SZ, values x:632 y:0
Tried to fiddle those numbers up and down a little bit, but log file from tokentool still has that same window position line.

**Comment by Phergus** [comment]
That probably means it's somewhere else.  TT 2.0 is a new build using JavaFX and that may be enough to move those prefs somewhere else.  I'll poke around.

**Comment by Phergus** [comment]
Try this one:
Computer\HKEY_CURRENT_USER\Software\JavaSoft\Prefs\net\rptools\tokentool\client

**Comment by Shotty4Life** [comment]
Yup, that was it.
Found two registry keys (window_x and window_y) whit a whooping value of -32000
Set both to 0 and tokentool appeared at the corner of my screen as if nothing was ever wrong.

Thanks a ton.
... Note to self: Write down the location of those registries in case this happens again.

**Comment by Phergus** [comment]
Glad that fixed it.  Now that the info is posted here hopefully the next person will be able to find it.

**Comment by JamzTheMan** [comment]
FYI In Windows, you can press  Windows key + left/right arrow to force an application to the next monitor.

Also, TokenTool 2.1 has a "reset" menu option than will 0 out the coordinates and screen size (resets all saved preferences) and can be accessed via a shortcut key.

**Comment by Azhrei** [comment]
I saw you closed this, but I don't see a resolution to the window geometry being set to negative values.  Is that covered somewhere else?  Or is it something that Java or JavaFX or Windows does that you don't have control over?  Just curious...

**Comment by Phergus** [comment]
> Also, TokenTool 2.1 has a "reset" menu option than will 0 out the coordinates and screen size (resets all saved preferences) and can be accessed via a shortcut key.

No hot key shown in the Menu.   And will it even work if the window is off display?   With the window active but mostly off the display, I couldn't access the reset (Alt -> H -> R) until I dragged it back on screen.

**Comment by JamzTheMan** [comment]
That's because negative geometry is valid. That's how multiple monitors work. X,Y is relative to the main monitor where negative coords are to the left or down of main monitor.

**Comment by JamzTheMan** [comment]
@Phergus that's unfortunate. I thought a shortcut was added but also Surprised alt h r didn't work...

**Comment by Azhrei** [comment]
I realize about negative geometry.  Just wondering why it isn’t corrected automatically when the window is reopened.  Does Windows require that every app check for that itself?  Annoying if every graphical app has to check to see if its main window is visible and correct for it...

**Comment by Phergus** [comment]
@JamzTheMan I kind of expected it to work as well.  Good news is that if I go into the registry and force it offscreen that I was able to use Alt-H-R to open the confirmation dialog and reset it.

However Windows-Left Arrow/Right Arrow did not work.
