### ISSUE TITLE
The mask seems to not be working

### ISSUE THREAD

**Issue by Wenneker** [RPTools/TokenTool#15]
When I make a token, the WHOLE image is being included, with the token overlay on top, but the creature's image also appears - both within the overlay, and ... OUTSIDE of the overlay, which wasn't how it worked in 1.0.

Is that an intended shift?

**Comment by JamzTheMan** [comment]
Nope, check your options. Specifically that you have Clip Portrait checked...

![image](https://user-images.githubusercontent.com/8051654/55271351-6aedca80-5279-11e9-92a3-eb2b5c87a554.png)
