### ISSUE TITLE
MacOS - Issue with Capture Screen function

### ISSUE THREAD

**Issue by Aventhar** [RPTools/TokenTool#16]
MacOS Mojave - TokenTool 2.0

When I use the Capture Screen function it works fine the first time. The second and any further times I try it,  it captures the transparent green capture box and button as part of the captured image.

I have tried removing and re-installing TokenTool, but same every time...

This does not seem to happen with the Windows version - at least not for me.

**Comment by Azhrei** [comment]
Hm, interesting.  I've never used the screen capture in TT, I'll try it out.

On High Sierra on my MBP, it captured the button and capture box on the first attempt.  I.e., it didn't work, even the first time.

Thanks for reporting this!

**Comment by JamzTheMan** [comment]
Can someone try this using 2.1 and see if the issue persists on Mac OS?

**Comment by Aventhar** [comment]
I’ll give it a shot today. Thanks!

________________________________________________________
Sean
seanlanoue@me.com

**Comment by JamzTheMan** [comment]
k, 2.1 should release sometime later today, keep an eye out.

**Comment by Aventhar** [comment]
I  loaded  up 2.1rc3 and the issue appears to be fixed at least for me. Thanks!

**Comment by Aventhar** [comment]
I tried the full release version of 2.1 also - Looking good - Thank You!
