### ISSUE TITLE
TokenTool does not start

### ISSUE THREAD

**Issue by fw** [RPTools/TokenTool#175]
**Describe the bug**

After installing, TokenTool does not start, and also not appear the splashscreen and any error dialogs.

**TokenTool Info**
- Version: 2.2.0-rc.1
- Install: Upgrade from 2.1, and New

**Desktop**
- OS: Windows
- Version: 10 Pro x64 20H2
- Locale: Japanese

**Additional Context**
- I had tried install two locations, ``%USERPROFILE%\AppData\Local\TokenTool`` and ``C:\App\TokenTool``. I got same results.
- MapTool 1.8.x also did not start in Japanese locale. Perhaps, is it same problem? (I changed locale to English and tried, but TokenTool did not launch.)
- After trying to start TokenTool, a error log file was produced in installed direcotory.

[hs_err_pid15508.log](https://github.com/RPTools/TokenTool/files/6478660/hs_err_pid15508.log)

**Comment by Phergus** [comment]
Did TT 2.1 work for you?

@fw you might try with the Java 16 build.

**Comment by fw** [comment]
Yes, TT 2.1 works well.
And, TT 2.2 is also installed and started correctly.
Thanks for updating!

**Comment by fw** [comment]
I tried to install by both installer of `.exe` and `.msi`.
Both installers are fine.

**Comment by Phergus** [comment]
Good to hear!  Thanks.

Closing.
