### ISSUE TITLE
Unable to resize image in the token tool window?

### ISSUE THREAD

**Issue by bschollnick** [RPTools/TokenTool#19]
Maybe I missed something, but I can't find any documentation for Token tool?

If this feature doesn't exist currently, then please consider this a feature enhancement request.

If I import a 800x1029 (eg. 
![deviantart_264864091_why not zoidberg](https://user-images.githubusercontent.com/979558/52520969-19906a00-2c3e-11e9-9c62-9962ab76a1bf.jpg) image, I see no way to resize the image to fit a decent portion of it into the 256x256 token.

Yes I could resize the token larger, but wouldn't I then need to resize the token smaller in Maptool to fit into a 1in sq?

Now, I'm new to this, I just started using maptool a week or two ago, so I'm still learning.  

But it seems like we should have some degree of image resizing in token tool, to help us capture the portion of the token that we would like.

**Comment by Phergus** [comment]
1.  Use the mouse wheel to resize either up or down.
2.  No, you wouldn't have to resize the token smaller in MapTool.  The default is that when you drop an image on to a map in MapTool, it is set to a single square/hex in size.  Technically the size is the map's Pixels per Grid setting.  You can also set a tokens size via the right-click menu.

Questions like these are easily answered on the [forums](http://forums.rptools.net/) or the [Discord server](https://discord.gg/crpk7FM).

**Comment by Azhrei** [comment]
But there should be some kind of documentation that tells users to use the mouse wheel.  At least in MapTool, there's the tips that show up in the status bar at the bottom of the window...  Something to think about for the next iteration of TT.

**Comment by JamzTheMan** [comment]
Agreed, we need so doc writers! 😄 

Is there a doc for TT 1.x? It's mostly the same instructions with some additions (like meta+mousewheel to rotate as well)

**Comment by Azhrei** [comment]
What?  Documentation?  Pfft, we don't need no stinkin' documentation!

Um, no, I don't think there's anything for TT 1.x either.  We've had some forum folks say they were going to try to write some docs, but it's a daunting task, particularly going back and updating stuff when the software changes...

**Comment by Phergus** [comment]
Wait a sec.  There's rotation?  Somebody should document this tool.

Apparently it's Shift-Mousewheel.

**Comment by Azhrei** [comment]
@Phergus "Wait a sec. There's rotation? Somebody should document this tool."

You're hired! 😁
