### ISSUE TITLE
Release build should create an MSI for windows

### ISSUE THREAD

**Issue by cwisniew** [RPTools/TokenTool#194]
**Is your feature request related to a problem? Please describe.**
Like MapTool the release should create an MSI as well as an exe for windows

**Describe the solution you'd like**
For the release build to create an MSI as well as exe for windows

**Describe alternatives you've considered**
Not doing it :)

**Additional context**
For a variety of reasons it may not always be possible to get the exe install working.

**Comment by Phergus** [comment]
Tested.  MSI created and working.
