### ISSUE TITLE
The 2.2 installer does not contain overlays

### ISSUE THREAD

**Issue by Tdue21** [RPTools/TokenTool#205]
**Describe the bug**
When installing a fresh 2.2 there are no overlays available, but the default *Gear, Chrome*.

**To Reproduce**
1. Uninstall any previous TokenTool installations. 
2. Remove the ~\.tokentool-rptools if it exists. 
3. Install TokenTool 2.2. 
4. Start TokenTool and observe the lack of overlays. 

**Expected behavior**
I expected the default set of overlays to be included. 

**TokenTool Info**
- Version: 2.2.?
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
If I install TokenTool 2.1 FIRST, and THEN 2.2., the overlays are present. So it seems that the overlays have been left out of the installer. 
Trying to restore default overlays on a clean 2.2. does nothing.

**Comment by Phergus** [comment]
Problem wasn't that the overlays weren't in the installer package it's that the prior method of using Reflection to copy them into their folder didn't work with the new modules/JFX approach.

Reviewed PR.  Overlays now installing as expected.
