### ISSUE TITLE
Changing portrait does not work

### ISSUE THREAD

**Issue by trev-dev** [RPTools/TokenTool#296]
**Describe the bug**
When I load up TokenTool, and am presented with the default token (woman with gear frame), I go to portrait, change portrait, pick any image (and any format) from my hard disk, click OK. After this, the default portrait disappears and my image is not loaded.

**Screenshots**
![where-portrait-go](https://user-images.githubusercontent.com/28788713/153741296-bb3d2d1e-b3fa-4d2f-a8c8-1432498c5488.gif)

**TokenTool Info**
- Version:  2.2.1
- Install: Fresh .rpm install

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35

**Comment by Azhrei** [comment]
What format is your image?  Please run `file your_inage_name` and paste the output into your reply.

it would also be helpful to have the log file under `~/.tokentool-rptools`.

it is known that some image generation programs produce output which the Java libraries can’t handle for some reason.  Often, it’s enough to load the image into a separate paint program and write it back out.

**Comment by trev-dev** [comment]
Happy to supply the data.
> What format is your image? Please run file your_inage_name and paste the output into your reply.

I tried two formats, both exported from GIMP:  
`bartlebee.webp: RIFF (little-endian) data, Web/P image`

`bartlebee.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 300x300, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=GIMP 2.10.30, datetime=2022:02:12 14:24:45], progressive, precision 8, 420x559, components 3`

I've attached the output logs from `~/.tokentool-rptools`
[log.txt](https://github.com/RPTools/TokenTool/files/8056238/log.txt)

**Comment by trev-dev** [comment]
With revived curiosity I tried again with a .png image export from GIMP and token tool worked as expected, but I'll leave this open as I'm not sure if we actually want this problem. I feel like if there's some sort of failure, meaningful advice from TokenTool would be great :)

**Comment by Azhrei** [comment]
There's nothing in your log file to indicate any error, so if it's a Java library, it's being quiet about it.  This is likely going to be tough to track down.  I'm not the author of this tool, but maybe some additional debugging output surrounding the code that does the image import would help.  I'll post again here if it appears any additional logging would help.

**Comment by trev-dev** [comment]
Stale
