### ISSUE TITLE
Crash when dragging Token from preview to MapTool canvas

### ISSUE THREAD

**Issue by spacegiant** [RPTools/TokenTool#39]
**Describe the bug**
TokenTool crashes suddenly when dragging Token from preview to MapTool canvas.

**To Reproduce**
1. Create token by dragging PNG from Safari to MapTool canvas
1. Resize image using scroll on mouse
1. Left click and drag token from preview pane to MapTool
1. Experience crash and loss of clipboard on first but sometimes second token.
1. Mac system error report (Pasted at bottom)

**Expected behavior**
Should be able to always drag a token from preview to MapTools without crashing.

**Screenshots**

**TokenTool Info**
- Version: 2.1
- Install: Fairly new. Installed for a month or so. Seemed to work for a while without error from what I remember.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: Mojave 10.14.6

**Additional context**
Attached Mac System Error Report

[Mac System Error Report.txt](https://github.com/RPTools/TokenTool/files/3446038/Mac.System.Error.Report.txt)

**Comment by Phergus** [comment]
I assume you meant TokenTool 2.1?

Cannot reproduce on Windows with TokenTool 2.1 and MapTool 1.5.3 so may be  MacOS only issue.

**Comment by Azhrei** [comment]
Yeah, this is a macOS-specific bug.  From the dump:

> Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: _type > 0 && _type <= kCGSLastEventType'
terminating with uncaught exception of type NSException
abort() called

It looks like Objective-C assert output...  There may not be anything we can do about it.  Trigger it and make sure it's sent to Apple and they'll forward it to the OpenJDK team.  (Or at least, they have done that in the past...)

**Comment by spacegiant** [comment]
@Phergus @Azhrei Thanks for looking in to this.
Yes, it was TokenTool 1.2 and MapTool 1.4.1.8
I will follow advice and send the report to Apple. In the meantime, I've a workaround where I drag to an intermediary location (an app called Unclutter) and then in to Maptool. That's been working fine.

**Comment by Phergus** [comment]
@spacegiant You may want to checkout TT 2.1 that has a number of improvements.

**Comment by spacegiant** [comment]
Sorry. 2.1 is the version I'm using.

**Comment by JamzTheMan** [comment]
Next release will be using Adopt OpenJDK 15, we'll test again with next release and see if the bug still persists...

**Comment by Phergus** [comment]
@spacegiant You might grab the 2.2 test build and see if Drag n Drop works for you now.

**Comment by Phergus** [comment]
Tested by @rkathey on macOS with TT 2.2 Java 16 build.  No crashing dragging from TT preview to MapTool.
