### ISSUE TITLE
Finer control over image size needed

### ISSUE THREAD

**Issue by Phergus** [RPTools/TokenTool#40]
**Is your feature request related to a problem? Please describe.**
When using the mouse-wheel to resize the portrait image the steps can be too large making it difficult to get just the right size.

**Describe the solution you'd like**
Would like a way to make the size jumps smaller by perhaps using Ctrl-Mouse-Wheel to produce smaller steps.

**Additional context**
Original posted on [forums](https://forums.rptools.net/viewtopic.php?p=274426#p274227) by EvilNerf.

**Comment by JamzTheMan** [comment]
Control + Mousewheel no reduces zoom (and Control + Shift + Mousewheel for rotation) by a factor of 10 for finer control.

**Comment by Phergus** [comment]
Tested.
