### ISSUE TITLE
PSD not loading into Overlay Manager

### ISSUE THREAD

**Issue by BasiliskOnline** [RPTools/TokenTool#429]
I saw that PSD's with Magenta Masks were required for custom tokens, so i set one up as per thnis guide https://wiki.rptools.info/index.php/creating_TokenTool_Overlays, however when i try to import the PSD simply nothing happens.

Edit: I originally made the PSD in photoshop. I opened and re-saved it in Affinity Photo and it works for some reason, so I assume Photoshop has some sort of specific setting that was conflicting with this? (image mode? bit rate? color mode?) so if you run into this same problem, I guess re-open it in another less powerful editor and resave.

**Comment by Azhrei** [comment]
There are multiple things that can go wrong (layers that are not the same size, for example).  Perhaps the other tools auto-corrected for that?  In any case, thanks for the follow up post.  (In the future, there's a template to use when filing bug/problem reports.  Not following the template typically causes them to be closed without action.)
